# Generated by Django 2.1.7 on 2019-02-16 15:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlr_latlon', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('cod_munic', models.IntegerField()),
                ('cod_cnes', models.IntegerField()),
                ('nom_estab', models.CharField(max_length=255)),
                ('dsc_endereco', models.CharField(max_length=255)),
                ('dsc_bairro', models.CharField(max_length=255)),
                ('dsc_cidade', models.CharField(max_length=255)),
                ('dsc_telefone', models.CharField(max_length=255)),
                ('dsc_estrut_fisic_ambiencia', models.TextField()),
                ('dsc_adap_defic_fisic_idosos', models.TextField()),
                ('dsc_equipamentos', models.TextField()),
                ('dsc_medicamentos', models.TextField()),
                ('co_cep', models.CharField(max_length=15)),
            ],
        ),
    ]
