version: '3.7'

services:
  web:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - backend
  app:
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - database
    networks:
      - backend
    command: gunicorn -b 0.0.0.0:8000 hackathon.wsgi
  database:
    image: mdillon/postgis
    environment:
      - POSTGRES_DB=hackathon
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
    driver: bridge